source 'https://rubygems.org'

ruby '2.3.1'

gem 'sinatra'
gem 'rack-google-analytics'
gem 'rake'
gem 'puma'
gem 'compass'
gem 'bootstrap', '= 4.0.0.beta'
gem 'heroku-bouncer', github: 'heroku/heroku-bouncer'
gem 'platform-api'
gem 'dotenv'
gem 'pusher'
gem 'sidekiq'
gem 'odlifier'
gem 'pg'
gem 'sinatra-activerecord'

group :test do
  gem 'rspec'
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-jasmine'
  gem 'capybara'
  gem 'coveralls'
  gem 'jasmine'
  gem 'pry'
  gem 'actionpack'
  gem 'database_cleaner'
end
